
DELTA = 1e-200
MIN_LIMIT=DELTA
OTHER_KEY='Others'
NO_OF_ITEMS_ON_A_PAGE=10
MAX_NO_OF_ARTICLES_ALLOWED=100
TYPE_ALL='all'
TYPE_POPULAR='popular'
CATEGORY_ALL='all'
RATIO_KEY_WORD_REQUIRED=0.2
NO_OF_PCATEGORY = 4